# Generated by Django 3.1.1 on 2021-07-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210715_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_china',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_thai_inbound',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_thai_outbound',
            field=models.BooleanField(default=True),
        ),
    ]
