# Generated by Django 3.0.8 on 2021-07-05 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200722_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_dirty', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('max_quantity', models.IntegerField(default=90)),
            ],
        ),
        migrations.CreateModel(
            name='Packinglist',
            fields=[
                ('packing_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_dirty', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('con_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_list', to='store.Container')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('INTRANSIT', 'in_transit'), ('CANCELLED', 'cancelled'), ('DELIVERIED', 'cancelled'), ('INBOUNED', 'inbound'), ('PENDING', 'pending')], default='INBOUNED', max_length=255)),
                ('is_paid', models.BooleanField(default=False)),
                ('shipping_by', models.CharField(choices=[('OWNER', 'Owner Shipping'), ('SHIPPING PROVIDER', 'SHIPPING PROVIDER')], default='OWNER', max_length=25)),
                ('is_dirty', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=255)),
                ('brand', models.CharField(db_index=True, max_length=255)),
                ('packing_type', models.CharField(db_index=True, max_length=255)),
                ('canton', models.IntegerField()),
                ('weight', models.CharField(db_index=True, max_length=255)),
                ('wight', models.CharField(db_index=True, max_length=255)),
                ('lenght', models.CharField(db_index=True, max_length=255)),
                ('height', models.CharField(db_index=True, max_length=255)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_dirty', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('packing_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_list', to='store.Packinglist')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('location', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='season',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sack_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='containers', to='store.Sack'),
        ),
    ]
