# Generated by Django 3.1.1 on 2021-07-15 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210705_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerCBM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120)),
                ('cbm_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remark', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Sack',
            new_name='Shipment',
        ),
        migrations.RemoveField(
            model_name='packinglist',
            name='con_id',
        ),
        migrations.AddField(
            model_name='buyer',
            name='email',
            field=models.EmailField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='buyer',
            name='line_id',
            field=models.CharField(default='none', max_length=120),
        ),
        migrations.AddField(
            model_name='buyer',
            name='tel',
            field=models.CharField(default='none', max_length=220),
        ),
        migrations.AddField(
            model_name='buyer',
            name='zipcode',
            field=models.CharField(default='none', max_length=220),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='store.buyer'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.CharField(default='none', max_length=220),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(default='none', max_length=120),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='canton',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Container',
        ),
        migrations.AddField(
            model_name='buyercbm',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.buyer'),
        ),
    ]
