# Generated by Django 3.1.1 on 2021-07-16 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0008_buyer_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.CharField(default='', max_length=220),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='client_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='line_id',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='tel',
            field=models.CharField(default='', max_length=220),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='zipcode',
            field=models.CharField(default='', max_length=220),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('tel', models.CharField(default='', max_length=220)),
                ('is_in_thai', models.BooleanField(default=True)),
                ('is_in_china', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.employee'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
