# Generated by Django 3.1.1 on 2021-07-22 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210716_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='track_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='store.buyer'),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='sack_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='containers', to='store.shipment'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('INTRANSIT_CHINA', 'intransit_china'), ('INTRANSIT_THAI', 'intransit_thai'), ('OUTBOUND_THAI', 'outbound_thai')], default='INTRANSIT_CHINA', max_length=255),
        ),
        migrations.CreateModel(
            name='QrProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(upload_to='')),
                ('is_inbound_thai', models.BooleanField(default=False)),
                ('is_outbound_china', models.BooleanField(default=False)),
                ('is_outbound_thai', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_product', to='store.purchaseorderproduct')),
            ],
        ),
    ]
