# Generated by Django 3.1.1 on 2021-07-22 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210722_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='type',
        ),
        migrations.AddField(
            model_name='packinglist',
            name='status',
            field=models.BooleanField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='store.warehouse'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.BooleanField(default=False, max_length=255),
        ),
    ]
