# Generated by Django 3.1.1 on 2021-07-22 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210722_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='po_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po', to='store.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='is_ready',
            field=models.BooleanField(default=True),
        ),
    ]
