# Generated by Django 3.1.1 on 2021-07-25 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210725_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='packing_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packing_list', to='store.packinglist'),
        ),
    ]
