# Generated by Django 3.1.1 on 2021-07-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210725_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglist',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
