# Generated by Django 3.1.1 on 2021-07-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210725_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrproduct',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_code'),
        ),
    ]
