# Generated by Django 3.1.1 on 2021-07-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20210726_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrproduct',
            name='product_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
